# Generated by Django 5.1.7 on 2025-03-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='id',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='currency_id',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal_id',
            field=models.CharField(default='DEFAULT_JOURNAL_ID', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default='-', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='total_debit',
            field=models.DecimalField(decimal_places=2, default='-', max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
