# Generated by Django 5.1.7 on 2025-03-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialReceipt',
            fields=[
                ('or_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=255)),
                ('or_date', models.DateField()),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(max_length=50)),
                ('reference_number', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=255)),
            ],
        ),
    ]
