# Generated by Django 5.1.6 on 2025-04-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0002_alter_generalledgeraccount_account_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledgeraccount',
            name='account_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='generalledgeraccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='generalledgeraccount',
            name='gl_account_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
