# Generated by Django 5.1.6 on 2025-05-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollAccounting',
            fields=[
                ('payroll_accounting_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('payroll_hr_id', models.CharField(max_length=255)),
                ('date_approved', models.DateTimeField()),
                ('approved_by', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('online_payment', 'Online Payment')], max_length=50)),
                ('reference_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50)),
            ],
        ),
    ]
