# Generated by Django 5.1.6 on 2025-05-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollaccounting',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payrollaccounting',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
