# Generated by Django 5.1.6 on 2025-05-01 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_accounting', '0002_alter_payrollaccounting_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollaccounting',
            options={'managed': False},
        ),
    ]
