# Generated by Django 5.1.6 on 2025-05-01 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_accounting', '0003_alter_payrollaccounting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollaccounting',
            options={},
        ),
    ]
