# Generated by Django 5.1.6 on 2025-05-01 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payroll_options'),
        ('payroll_accounting', '0004_alter_payrollaccounting_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollaccounting',
            name='approved_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payrollaccounting',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payrollaccounting',
            name='payroll_accounting_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payrollaccounting',
            name='payroll_hr_id',
            field=models.ForeignKey(db_column='payroll_hr_id', on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll'),
        ),
        migrations.AlterField(
            model_name='payrollaccounting',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='payrollaccounting',
            table='payroll_accounting',
        ),
    ]
