# Generated by Django 5.1.6 on 2025-05-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_accounting', '0005_alter_payrollaccounting_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollJournalView',
            fields=[
                ('payroll_accounting_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('payroll_hr_id', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=255)),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('employment_type', models.CharField(max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overtime_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overtime_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('holiday_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('thirteenth_month_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_bonuses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sss_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('philhealth_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagibig_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('late_deduction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('absent_deduction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('undertime_deduction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=50)),
                ('date_approved', models.DateTimeField()),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'payroll_journal_view',
                'managed': False,
            },
        ),
    ]
