# Generated by Django 5.1.7 on 2025-03-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedgerAccount',
            fields=[
                ('gl_account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('account_code', models.CharField(max_length=255)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'general_ledger_accounts',
            },
        ),
    ]
