# Generated by Django 5.1.7 on 2025-03-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('account_code', models.IntegerField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'chart_of_accounts',
                'managed': False,
            },
        ),
    ]
