# Generated by Django 5.1.6 on 2025-04-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialreport',
            options={'managed': False},
        ),
    ]
