# Generated by Django 5.1.6 on 2025-04-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_report', '0002_alter_financialreport_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='financialreport',
            table='financial_report',
        ),
    ]
