# Generated by Django 5.1.6 on 2025-04-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'managed': False},
        ),
    ]
