# Generated by Django 5.1.7 on 2025-04-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entry_lines', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalEntryLine',
        ),
    ]
