# Generated by Django 5.1.6 on 2025-04-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'admin.currency',
                'managed': False,
            },
        ),
    ]
