# Generated by Django 5.1.6 on 2025-04-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={},
        ),
    ]
