# Generated by Django 5.1.6 on 2025-04-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_currency_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='id',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='name',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='status',
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_id',
            field=models.CharField(default='currency_id', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_name',
            field=models.CharField(default='currency_name', max_length=255),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterModelTable(
            name='currency',
            table='"admin"."currency"',
        ),
    ]
