# Generated by Django 5.1.6 on 2025-04-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_remove_currency_id_remove_currency_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'managed': False},
        ),
    ]
