# Generated by Django 5.1.7 on 2025-04-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialreceipt',
            name='settled_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='officialreceipt',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='officialreceipt',
            table='official_receipts',
        ),
    ]
