# Generated by Django 5.1.6 on 2025-05-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_receipts', '0002_officialreceipt_settled_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialreceipt',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='officialreceipt',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
