# Generated by Django 5.1.6 on 2025-05-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_receipts', '0003_alter_officialreceipt_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialreceipt',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='officialreceipt',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
