# Generated by Django 5.1.6 on 2025-04-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('delivery_note_id', models.CharField(max_length=255)),
                ('is_returned', models.BooleanField(default=False)),
                ('invoice_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': '"sales"."invoice"',
                'managed': False,
            },
        ),
    ]
