# Generated by Django 5.1.6 on 2025-04-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_id', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoice',
            table='"sales"."sales_invoices"',
        ),
    ]
