# Generated by Django 5.1.6 on 2025-05-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsPayableReceipt',
            fields=[
                ('ap_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('paid_by', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'accounts_payable_receipts',
                'managed': False,
            },
        ),
    ]
