# Generated by Django 5.1.7 on 2025-03-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('entry_line_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gl_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('journal_id', models.CharField(blank=True, max_length=255, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'general_ledger_jel_view',
                'managed': False,
            },
        ),
    ]
