# Generated by Django 5.1.6 on 2025-05-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRemittance',
            fields=[
                ('remittance_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('deduction_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHECK', 'Check')], max_length=50)),
                ('reference_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=50)),
            ],
        ),
    ]
