# Generated by Django 5.1.6 on 2025-05-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_and_remittance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollremittance',
            options={'managed': False},
        ),
    ]
