# Generated by Django 5.1.6 on 2025-05-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_and_remittance', '0002_alter_payrollremittance_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payrollremittance',
            table='tax_and_remittances',
        ),
    ]
