# Generated by Django 5.1.7 on 2025-04-01 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entry', '0002_remove_journalentry_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryLines',
            fields=[
                ('entry_line_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gl_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('journal_id', models.ForeignKey(db_column='journal_id', on_delete=django.db.models.deletion.CASCADE, to='journal_entry.journalentry')),
            ],
            options={
                'db_table': 'journal_entry_lines',
            },
        ),
    ]
