# Generated by Django 5.1.7 on 2025-04-08 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0001_initial'),
        ('journal_entry', '0003_journalentrylines'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('entry_line_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('gl_account_id', models.ForeignKey(blank=True, db_column='gl_account_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='general_ledger.generalledgeraccount')),
                ('journal_id', models.ForeignKey(db_column='journal_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='journal_entry.journalentry')),
            ],
            options={
                'db_table': 'journal_entry_lines',
            },
        ),
        migrations.DeleteModel(
            name='JournalEntryLines',
        ),
    ]
