# Generated by Django 5.1.6 on 2025-04-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entry', '0004_journalentryline_delete_journalentrylines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='total_debit',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
    ]
