# Generated by Django 5.1.6 on 2025-04-16 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0002_alter_generalledgeraccount_account_code_and_more'),
        ('journal_entry', '0004_journalentryline_delete_journalentrylines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentryline',
            name='gl_account_id',
            field=models.ForeignKey(blank=True, db_column='account_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='general_ledger.generalledgeraccount', to_field='account_code'),
        ),
    ]
